[parity]
chain = "./spec/spec.json"
base_path = "./nodes/parity_validator_/"

[network]
port = 30301
discovery=true
reserved_peers="./nodes/reserved_peers"

[rpc]
cors = ["null"]
hosts = ["all"]
port = 8550
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]

[account]
unlock = []
password = ["./nodes/parity_validator_/node.pwd"]

[mining]
force_sealing = true
engine_signer = ""
reseal_on_txs = "none"

[websockets]
disable = false
port = 8750
interface = "all"
origins = ["all"]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "secretstore"]
hosts = ["all"]